cargo-features = ["workspace-inheritance"]

[package]
name = "backfill-onboarding-fees"
version = "0.0.1"
edition = "2021"

[profile.release]
overflow-checks = true

[dependencies]
solana-client = "1.14.11"
serde_json = "1.0"
reqwest = { version = "0.11.13", features = ["blocking", "json"]  }
serde = "1.0.152"
solana-sdk = "1.14.11"
bincode = "1.3.3"
warp = "0.3.3"
futures = "0.3.25"
lazy_static = "1.4.0"
anchor-lang = "0.26.0"
clap = { version = "4.3.9", features = ["derive"] }
tokio = "1.29.0"
anchor-client = "0.26.0"
anyhow = "1.0.71"
chrono = "0.4.26"
helium-entity-manager = { git = "https://github.com/helium/helium-program-library", features = [ "no-entrypoint" ] }
helium-sub-daos = { git = "https://github.com/helium/helium-program-library", features = [ "no-entrypoint" ] }
hpl-utils = { git = "https://github.com/helium/helium-program-library", branch = "develop" }
bs58 = "0.4.0"
sha2 = "0"
