compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: db72366acb4a84405bcffb649cdfdcf7556a2be0b2bfa4de9cd619f5a32af285529c56d26d5849bf9c09718895a3b8919798c26e1de3375c9c58c41d484bd8b2
    path: .yarn/plugins/@yarnpkg/plugin-deploy-lockfiles.cjs
    spec: "https://raw.githubusercontent.com/zaro/yarn-plugin-deploy-lockfiles/main/bundles/%40yarnpkg/plugin-deploy-lockfiles.js"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
