nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-deploy-lockfiles.cjs
    spec: "https://raw.githubusercontent.com/zaro/yarn-plugin-deploy-lockfiles/main/bundles/%40yarnpkg/plugin-deploy-lockfiles.js"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
