name: "Setup Anchor"
description: "Setup Anchor"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup/
    - uses: ./.github/actions/setup-solana/
    - run: rustup install 1.85.0 && rustup default 1.85.0
      shell: bash
      if: steps.cache-anchor-cli.outputs.cache-hit != 'true'
    - uses: actions/cache@v4
      name: Cache Anchor Cli
      id: cache-anchor-cli
      with:
        path: |
          ~/.cargo/bin/anchor
        key: anchor-cli-${{ runner.os }}-v0003-${{ env.ANCHOR_VERSION }}-${{ env.ANCHOR_SHA }}
    # if ANCHOR_VERSION is 0, then install the anchor-cli from source
    - run: if [ $ANCHOR_VERSION -eq 0 ]; then cargo install --git https://github.com/coral-xyz/anchor --rev $ANCHOR_SHA anchor-cli --locked --force; else cargo install --git https://github.com/coral-xyz/anchor --tag "v$ANCHOR_VERSION" anchor-cli --locked; fi
      shell: bash
      if: steps.cache-anchor-cli.outputs.cache-hit != 'true'
    - uses: actions/cache@v4
      name: Cache Toml Cli
      id: cache-toml-cli
      with:
        path: |
          ~/.cargo/bin/toml
        key: toml-cli-${{ runner.os }}-v0002
    - run: (cargo install toml-cli || true)
      if: steps.cache-toml-cli.outputs.cache-hit != 'true'
      shell: bash
