cargo-features = ["workspace-inheritance"]

[package]
name = "migration-tx-executor"
version = "0.0.1"
edition = "2021"

[profile.release]
overflow-checks = true

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
solana-client = "1.14.11"
serde_json = "1.0"
reqwest = { version = "0.11.13", features = ["blocking", "json"]  }
serde = "1.0.152"
solana-sdk = "1.14.11"
indicatif = "0.17.2"
bincode = "1.3.3"
tokio = { version = "1.23.0", features = ["full"] }
warp = "0.3.3"
prometheus = { version = "0.13.3", features = ["process"] }
lazy_static = "1.4"
futures = "0.3.25"
hpl-utils = { path = "../hpl-utils" }