[package]
name = "hpl-crons"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "hpl_crons"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
tuktuk-program = { git = "https://github.com/helium/tuktuk.git", branch = "initial-commit" }
spl-token = { version = "^3.3.1", features = ["no-entrypoint"] }
