name: "Setup ts"
description: "Setup ts"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: pnpm/action-setup@v4
    - uses: actions/cache@v4
      name: Cache Typescript node_modules
      id: cache-typescript-node-modules
      with:
        path: |
          ./node_modules/
          ./packages/*/node_modules/
        key: node-modules-${{ runner.os }}-v0002-${{ env.NODE_VERSION }}-${{ hashFiles('./pnpm-lock.yaml') }}-${{ hashFiles('./**/*/package.json') }}
    - run: pnpm install --frozen-lockfile
      shell: bash
      if: steps.cache-typescript-node-modules.outputs.cache-hit != 'true'
    - run: pnpm run build
      shell: bash
