@startuml

skinparam linetype polyline

control crank


frame Solana {
  collections hotspots [
    Hotspot NFTs
  ]
  component lazy_distributor {
    card rewards_escrow
  }
  component hotspot_issuer
  component data_credits
  component helium_sub_daos {
    card hnt_mint
    card dnt_mint
  }
  component treasury_management {
    card sub_dao_treasury
  }

  card user_wallet

  dnt_mint --> rewards_escrow : DNT
  rewards_escrow --> user_wallet : DNT

  hnt_mint --> sub_dao_treasury : Mint HNT

  hotspot_issuer --> hotspots : Create

  hotspots --> lazy_distributor

  hotspot_issuer --> helium_sub_daos : Device Count

  data_credits --> helium_sub_daos : DC Burned

  hotspot_issuer --> data_credits : Burn DC
}

collections oracles [
  DNT Rewards Oracle
]

agent wallet [
  Wallet App
]

agent maker [
  Maker App
]

agent onboarding [
  Onboarding Server
]

hnt_mint <- crank  : issue rewards
dnt_mint <- crank  : issue rewards

maker <- onboarding : issue hotspot, assert location tx

maker --> hotspot_issuer : issue hotspot, assert location tx

oracles --> wallet : set and distribute rewards tx

lazy_distributor <-- wallet  : set and distribute rewards

helium_sub_daos --> treasury_management : set_expiry


@enduml
