name: NPM Publish

env:
  SOLANA_CLI_VERSION: 2.1.6
  NODE_VERSION: 24.13.1

permissions:
  id-token: write # Required for OIDC
  contents: read

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v0.0.1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup/
      - uses: ./.github/actions/setup-anchor/
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - uses: ./.github/actions/build-anchor/
        with:
          testing: false
          devnet: false
      - uses: ./.github/actions/setup-ts/
      - name: Lerna Publish
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
